all: c3 

ProdCons3: ProdCons3.java
		javac -g ProdCons3.java

c3: prodcons2.cpp
		g++ -pthread -g queue.cpp prodcons2.cpp

ProdCons2: ProdCons2.java
		javac -g ProdCons2.java

Prod1: ons1.java
		javac -g ProdCons1.java


clean:
	rm *.class .*.*.swp 
